//
// Created by Zhen Guan on 2023-03-15.
//

#pragma once


constexpr int CONFIG_BUFFER_SIZE = 8192;
constexpr int CONFIG_INPUT_SIZE = 1024;

#define CONFIG_HISTORY_MAX 100

#define CONFIG_ENV_HOME "HOME"
#define CONFIG_ENV_PATH "PATH"

#define COLOR_RESET 0
#define COLOR_RED 31
#define COLOR_GREEN 32
#define COLOR_YELLOW 33
#define COLOR_BLUE 34
#define COLOR_MAGENTA 35
#define COLOR_CYAN 36
#define COLOR_WHITE 37
#define COLOR_GREY 90

#define COLOR_BRIGHT_RED 91
#define COLOR_BRIGHT_GREEN 92
#define COLOR_BRIGHT_YELLOW 93
#define COLOR_BRIGHT_BLUE 94
#define COLOR_BRIGHT_MAGENTA 95
#define COLOR_BRIGHT_CYAN 96
#define COLOR_BRIGHT_WHITE 97

